version: '3'
services:
  user-rpc:
    build:
      context: .
      dockerfile: apps/user/rpc/Dockerfile
    image: user-rpc-image
    ports:
      - "10000:10000"
    depends_on:
      - mysql
      - etcd
      - redis
    networks:
      z-chat:

  user-api:
    build:
      context: .
      dockerfile: apps/user/api/Dockerfile
    image: user-api-image
    ports:
      - "10001:10001"
    depends_on:
      - mysql
      - etcd
      - redis
    networks:
        z-chat:

  social-rpc:
    build:
      context: .
      dockerfile: apps/social/rpc/Dockerfile
    image: social-rpc-image
    ports:
      - "10002:10002"
    depends_on:
      - mysql
      - etcd
      - redis
    networks:
      z-chat:

  social-api:
    build:
      context: .
      dockerfile: apps/social/api/Dockerfile
    image: social-api-image
    ports:
      - "10003:10003"
    depends_on:
      - mysql
      - etcd
      - redis
    networks:
      z-chat:

  redis:
    image: redis:alpine3.18
    ports:
      - "16379:6379"
    container_name: redis
    volumes:
      - ./components/redis/data:/data
      - ./components/redis/config/redis.conf:/usr/local/redis/config/redis.conf
    environment:
      TZ: Asia/Shanghai
    restart: always
    networks:
      z-chat:

  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: etcd
    ports:
      - "12379:2379"
      - "12380:2380"
    environment:
      - ETCD_ENABLE_V2=true
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://192.168.0.111:12379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_NAME=etcd
    volumes:
      - ./components/etcd/data:/bitnami/etcd/data
      - ./components/etcd/logs:/bitnami/etcd/logs
    networks:
      z-chat:

  mysql:
    image: mysql:5.7
    ports:
      - "13306:3306"
    container_name: mysql
    volumes:
      - ./components/mysql/data:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    environment:
      MYSQL_ROOT_PASSWORD: wpzyyds
    restart: always
    networks:
      z-chat:

networks:
  z-chat:
    driver: bridge